export const ADD_FOUND_PERSON= 'ADD_FOUND_PERSON';
export const UPDATE_FOUND_PERSON= 'UPDATE_FOUND_PERSON';
export const DELETE_FOUND_PERSON= 'DELETE_FOUND_PERSON';
export const FETCH_FOUND_PERSON= ' FETCH_FOUND_PERSON';